package StorePermissin;

public enum Permission {
    VIEW_AND_RESPOND_TO_USERS,
    VIEW_STORE_HISTORY,
    EDIT_EXISTING_PRODUCT,
    ADD_NEW_PRODUCT,
    EDIT_PRODUCT,
    REMOVE_PRODUCT,
    EDIT_STORE_POLICY,
    ASSIGN_STORE_MANAGER,
    REMOVE_STORE_MANAGER,
    ADD_REVIEW_TO_PRODUCT,
    REPLY_TO_FORUM,
    CLOSE_STORE,
    OPEN_STORE,
    INFO_OF_MANAGERS,
    ;



}
