package Store;

public enum ProductsCategories {
    Other,
    Appliances,
    Apps$Games,
    Arts$Crafts$Sewing,
    Automotive_Parts$Accessories,
    Baby,
    Beauty$Personal_Care,
    Books,
    CDs$Vinyl,
    Cell_Phones$Accessories,
    Clothing$Shoes$Jewelry,
    Collectibles$Fine_Art,
    Computers,
    Electronics,
    Garden$Outdoor,
    Grocery$Gourmet_Food,
    Handmade,
    Health$Household$Baby_Care,
    Home$Kitchen,
    Industrial$Scientific,
    Movies$TV,
    Office_Products,
    Pet_Supplies,
    Sports$Outdoors,
    Tools$Home_Improvement,
    Toys$Games,
    Video_Games,

    }
